version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: api
    volumes:
      - db_data:/var/lib/mysql

  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    container_name: minio
    volumes:
      - ./data:/data
      - ./minio-policies:/root/.minio/policies # Mount the policy directory
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data

  redis:
    image: redis:6.2
    container_name: redis_cache
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
